services: 
  selenium_server_chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium_server_chrome
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: "2g"
    restart: unless-stopped

  selenium_server_chromium:
    image: selenium/standalone-chromium:latest
    container_name: selenium_server_chromium
    ports:
      - "4445:4444"
      - "5901:5900"
    shm_size: "2g"
    restart: unless-stopped

  selenium_server_firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium_server_firefox
    ports:
      - "4446:4444"
      - "5902:5900"
    shm_size: "2g"
    restart: unless-stopped

  selenium_server_edge:
    image: selenium/standalone-edge:latest
    container_name: selenium_server_edge
    ports:
      - "4447:4444"
      - "5903:5900"
    shm_size: "2g"
    restart: unless-stopped

  jupyter_selenium:
    build: "./jupyter"
    container_name: jupyter_selenium
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/selenium_test.ipynb:/home/jovyan/selenium_test.ipynb
    restart: unless-stopped
